apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workloadrepo2
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCTmjYvGXfqfCadvGf7T7CsBswYkEd9bBNIAPGRCzW+HDFIOVPBCo153gwXY3G6oZK4kcaSxvpSbkF6Q5MdOpLe9MZlYbFvRgIixbJE882B9YwJQ9ukzt8Q0KEFQo4+H2kVwCJOAYlSIJ4hCmirXelUdo8chmGGlZr4g2s5q+fv4aLs30oA/NIeSi884DUoQhE7O88cPa5CmFddlbSMxSpqphQq5rzEZZS7EsbKgT/O0AStau4kvqzRkhxDLJy3486NQYlSpyqvxkUPxBUV5mskxLUVdgmrmM9v6VOW+KF8Ox8VRrAtgdvpY3/5xob+Jc2+zzwy8szfEitU4Pp22AcLcIzdSsCqrVkV/i2ksVBbG6GBkn3yrXnQhjPatcuxgweHPSPJh74PPEdKsnfIW8CZi5aT2LDdoKo=
  template:
    metadata:
      creationTimestamp: null
      name: workloadrepo2
      namespace: default

