apiVersion: eaas.envmgmt.io/v1
kind: EnvironmentTemplate
metadata:
  name: vijaysamanthapuri-frav-et
  project: vijaysamanthapuri-frav
spec:
  agents:
  - name: em-gitops-agent
  resources:
  - kind: resourcetemplate
    name: vijaysamanthapuri-frav-rt
    resourceOptions:
      version: v1
    type: dynamic
  - dependsOn:
    - name: vijaysamanthapuri-frav-rt
    kind: resourcetemplate
    name: vijaysamanthapuri-frav-rt-python
    resourceOptions:
      version: v1
    type: dynamic
  variables:
  - name: username
    options:
      displayMetadata:
        disabled: false
        section: ""
        sectionDescription: ""
        tooltip: ""
        weight: ""
      override:
        type: allowed
      required: true
    valueType: text
  version: v1
  versionState: draft
