apiVersion: eaas.envmgmt.io/v1
kind: EnvironmentTemplate
metadata:
  name: vijaysamanthapuri-frav-et
  project: vijaysamanthapuri-frav
spec:
  agents:
    - name: em-gitops-agent
  resources:
    - kind: resourcetemplate
      name: vijaysamanthapuri-frav-rt
      resourceOptions:
        version: v1
      type: dynamic
  version: v1
  versionState: draft
