apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-delete-hook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fail-uninstall
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "This pre-delete hook is intentionally failing"
              exit 1
