apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: vijaysamanthapuri-frav-rt-intermediate
  project: vijaysamanthapuri-frav
spec:
  agents:
    - name: em-gitops-agent
  contexts:
    - name: vijaysamanthapuri-frav-rafay-cc
  provider: opentofu
  providerOptions:
    openTofu:
      backendType: system
  repositoryOptions:
    branch: main
    directoryPath: /terraform/intermediate/
    name: github-rafay-training
  version: v1
  versionState: draft
