apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    test: test1
  name: vijayseks300326-1
  project: defaultproject
spec:
  blueprintConfig:
    name: default
    version: latest
  cloudCredentials: disney-eks-test-role
  config:
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    iam:
      serviceAccounts:
      - attachPolicy:
          Statement:
          - Action: ec2:DescribeInstances
            Effect: Allow
            Resource: '*'
            Sid: VisualEditor0
          Version: "2012-10-17"
        metadata:
          name: testsa
          namespace: default
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: al2023-3
      privateNetworking: false
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      volumeSize: 100
      volumetype: gp3
    metadata:
      name: vijayseks300326-1
      region: us-west-2
      tags:
        email: vijaysamanthapuri@rafay.co
        env: cs-demo
      version: "1.33"
    network:
      cni:
        name: aws-cni
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: true
      nat:
        gateway: Single
  crossAccountRoleArn: arn:aws:iam::211125364662:role/sample-disney-role
  type: aws-eks
