apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vijaysamanthapuri-frav-cc
  namespace: default
spec:
  encryptedData:
    TF_VAR_secret.: AQBRPKMN+2kOfF6jnYUTKt3w2WnCxJxDQoZys6hATezMxNgtf2kVqMMyD9iQuOOXswa2wCk7A7TYgO272d+tJ44iNennduYHff3Rl0q7aKfnw6NuhIHo0HpHmJiswuRg46wDurzKE5coqXBO7SR85qoq7NMtP7sGt9v868q2jpQYSETrkOFqPXPs1sAKBSABVUZo5GhKiczf5QPDzgSr43et5V5ZErQR7JdzIjfuiimfvdnAzCB7Js7Trw6bSlDARHy5FrpnMs94xnOA4F58dAnSex2XBuVe07HzzRJi3NDHYF1etNLQa1c4XfBlD63I9XWXnyqM4+KhRjCb9AJYj+LMHgBLTtCs9JdLHjCYv3x1r6QGdBJbhYt6rQ==
  template:
    metadata:
      creationTimestamp: null
      name: vijaysamanthapuri-frav-cc
      namespace: default

