apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: vijaysamanthapuri-frav-env3
  project: vijaysamanthapuri-frav
spec:
  template:
    name: vijaysamanthapuri-frav-et
    version: v1
    versionState: unspecified
  variables:
  - name: username
    options:
      displayMetadata:
        disabled: false
        section: ""
        sectionDescription: ""
        tooltip: ""
        weight: ""
      override:
        type: allowed
      required: true
    value: vijaysamanthapuri
    valueType: text
