apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: vijaysamanthapuri-frav-env2
  project: vijaysamanthapuri-frav
spec:
  template:
    name: vijaysamanthapuri-frav-et
    version: v1
    versionState: unspecified
