apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tfdemo1
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDN7vc6F7+8Wgv3o3KWw7TvtuTtsns9KasLVWzNWbTSvTpbHr9TWs5pZfyJMow+f4/KWTJhimDOPewIudNDy+NLMKlZ2+3ky0fPOanOc/puH3jch9J4STyVPLxzzNUgJTALPld5FfTapK0fU1WxafTJEvzDOEXO/vvtaFtx5jSRLU9j+mggsHrchHNlmBGsQOw66k8i35pZUhqxOqYsAmPwODuDchcIrrUetzD9axGJAFJqjJSYEuB/F3gdRFuuW3de5vArVjFFcXSnLqJw2SGQ2uuHMlySlYaRj23+/9/ivEHWPGsrNXpzTOgk7OuWdEox3Nu0JtNu/EJdpu8DMT80/RhwyFcdIjRxt3+DU9FMscVibk674OdpDDxd1APOLT7Pj4+fTB7QwYioH0k/iKdWm0qNJK5MwuI=
  template:
    metadata:
      creationTimestamp: null
      name: tfdemo1
      namespace: default

