apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tfdemo1
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAewtnSFbjNkICOBXcth3kSyWtlMJLho9SDitks8FX4g6X3RJiXKwZb6I1a3ipR/YVXV3EGSAgUEVp7uRt1bguKHKrtJiwAwXtAn7I/Cqy6cEtRc+m1hHqenMoDNiJjlZl+kY98hSng3MReEk2iOKUd4CYyqn4hCdlWzMlHgQIGJpanut/04CMkzcOHi0Nt+t+DSOm+Na2P9cfVzys+UGk+uDjmgj9DqNwfve540oz7VE0AzUw9sxCjLsy5JmgBOeprGyjewUW8rJ0JN/5rn/Owbp6ahrafoOCPNHTXUiLevaaROlEhcqT7hEUMFoStFw30IR0JWdDPQocxXhK5sgOxw5H4ZfHpN212Xk4pRuIMQe2QXfpamJaUQVAgn78ADrfQ/7uTbWKBsEnigVcB+e0WbRJEqShIIdk=
  template:
    metadata:
      creationTimestamp: null
      name: tfdemo1
      namespace: default

