apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tfdemo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAdE3xsKi9X/FjRcuGNpsB6NbSECFZZh7iv2AyAeelLqZoDAksEYA0CgpoidcXpGLCPhqYcZLWfE5/OofcmRI/l2YHxkqV856cJ/5gaUemwo7CeWp6ISn1C1q9JEsUufFxClrwKcRYFh48xWwDKeSoLq35TkSUxhofOc2T8srGmRrB3vb4f3cESAx7h0CYni0m836FTh+9G9iN6acbwIsImC0PtO7kiBsPDFqMW7jqWcSIlxyNMKAHzR2wXjlLQdQkIpyskGY204j6mNB2sdIHHJfUAC+ajOH8LA+q8IeaoXOlaC/rUvHvqFQiWQGXfluRSncyNbEZ+++IE2H0Ra7nhqq1MwbrobwFUlVE6+OXiq9hC+ekvvWuh6uEhR07HMaCJWcSLsb72PzwQlxdVFyg/n21t2MwUTvw=
  template:
    metadata:
      creationTimestamp: null
      name: tfdemo
      namespace: default

