apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tfdemo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQArzLFz4pBF4Q7BSc5rSuxZ/V6YwDwELP10DxG43PPHB/cK8533+rFUun4/QIuTpbptwhnLAzO3T+nE2uEnAW3j3UxkIcGDUlZ9r/YhkHaHWMXJf6+oah62vSVieumQa/efPcvzjAbNqwDcRh33TkMz2bi13fKTWCGgg2LMClBW7eWwTtFbQSWFPwYIcYrC+/jH4qBDd4CA24xsEMHzpw1cvYLe3QN2jWmowNreV5zosXGgZ8oyaGNEXx6m3BEdnY3LX2heoWSk8X3IsaeND31a4bkXndMixI1EBvVy5cl8eaoWilsQ5feknxrOqYZVCAdHlG+0z+/fDQm/slLISS79crKpZUYjyAi/kBzcIp8h10RvtPcVD0MuqsYQJ6TbND8N8PKxlm9yAKeyrwVH1JArxm+Dh2mVcV0=
  template:
    metadata:
      creationTimestamp: null
      name: tfdemo
      namespace: default

