apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAGSGq/96yoh/29/W5vrLUNUixDrkNIWBCKjqAzsyncx1rUOPsqkg96tHXFF9KCUsDvf72q9g2fm1bSsfCZPqqaYkKvXBuHULt/5nHjcVzVlhviOwgkZAEn9/GFrJyr7RZDmePY+okvwg2wRKM4kaztJEvYke8J0nBXRE45CHVlBMOi6N0wKmhEDo9cGE2Wnw8HYNrwoANm0Maoigu8NDSHEWnoBxCJT053z2/XvA8Xm0niWB9Jec1VKclHAePyWN/WzotKPayhpm0FOL1fqItoe8cS2ZgKDr/DgiAOt3kJ2SI2MwjDQHRzWHJ0BMTsYxanmJml+WpNogMIUPLYX+krA9Pp+jqr4j0owm45p1sU9kIhsXH1P9NBkVG/nzVnHKQi4LevtVtB07xFTPH6xIU2fZ7b8IjvKDw=
  template:
    metadata:
      creationTimestamp: null
      name: system-sync
      namespace: default

