apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCD2CoKLW7FZjWq5XXd1sBtCofHmsiYLPbQ8ClfNRS23PsxFEe0y0qpvMc/EbfhcrUy3Diq4OaFC+CW6i+Io/5L+zeElTMZaQosVwSoDs2hvNArHYtLjg/f00rwJisiqpJ/wlxSkC5qwLnpv6Hxe+qzBM1VwJ5iuFsWhOKcPZ9aYT6Oq3NeYkNI3JrebhQUE1IDSBJPPjP6jGtuUczkKks2qfSlprNswFMy/WA+n0qgrrMjbcwcmsvASg0HVdZDPwuk1J486I8y20uHHKJNgNX2ZroghrNyNG2NCikegREfiCRvjEyXEZYoYfiP5byz2HzMqTmuZ7GR9gBPTnWkZhhJ0nAf6dAc42W/L6rQif0mEJulKjioX9qLBYMcjQP/4l+MfKdufY8A62epxPoaiFljVcDLgXgzeb0=
  template:
    metadata:
      creationTimestamp: null
      name: system-sync
      namespace: default

