apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helmsample1
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDx3hobKmTw7j7cHFQpHNtVqFqa3Qft+/nSHrqhDlXTylOvsUrwjUrZGc4gi/sy1AGipJUQxsoRQVLf7y0fp+6rEdNSvO3aFB1suOqVR+Tu2jWa1IKKamM7at7TmwCPgD+EaJDnyDU6s9xIRjyB/d2NyOJZ1rQcP4qteupGNjtBOXHhWQhIBANYADeIKr12bUxzCjh2f+P+gCgPAG/DIF5sQXqClOnmXrsd/6BEu1zbCNoqtLyhGkoy1wHY3QjzBRjsQDPUpiyhNbB1yL6alTpQG9kUBU4Vsuh+GY3oWVNBGc9hOqRcMKhxHAtllHYpQFyoin0QGfJDvZqAcGSgAD67xmUNGtnS0RNSkU3ZPRQY6JaCO6J1mCZ6iZKZHBSbMah3WUqJ80PpirMPNL/x5TxnCpGB139vmVY=
  template:
    metadata:
      creationTimestamp: null
      name: helmsample1
      namespace: default

