apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: helmsample1
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCZezIhE631EKvUkUQsc5TRcd1TnGgjXOgy00ERYL1knUpDVlZep3qAFNGhL1igS9qi6lqQPXFeXQ4DFwIXigO3vp9nbE0+/ToB0Z7v+0A9hGO1iIIEqfHiYb86iMCpkRc/7txQpgknC1DzFBry2SO5gwnnRMzmaEIRfGgQ3rX1CNEs3Wgxzl7wQ+ETDBocGtnymWDKCoZVImMch1IERtxmNd2lI5mr7TMnVTqprz0+ntyGf1IJzWW8wwR5Y/7d2MdprnErtwUjHpHpavreaSVxDuIM6mJK0Dpn6/7UvzeI6dZ3sAbPnr+i9tc9X9bnzDB+ODTKzM/rki+V+86wUeJ5iAMf+9akN2jnx7/4z2v6yc5pMaLgUyO8qcHt/G+FCeCnK7iKz6BANMs+l0CE7H48wPCTlw8KvG4=
  template:
    metadata:
      creationTimestamp: null
      name: helmsample1
      namespace: default

