apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: staggered-live1
  namespace: default
spec:
  encryptedData:
    variables.0.: AQAFoRbfNu+BYt/PTSJz9J5xpNWwPClxCF1dcHUMXFLtIPJYgueS1e4JPIbCy1GymCDquSiRbnpeE/2Ag1TuE7XGcnVKT51+0WB/IF5lbdpQPtjz/bxJEO+vzAp3BdAis8xx6+GxoXqDkXn5FDrsQ8+WDgE6Iak66x5W6EXfr7FJDu/F4OIQUT1ztCp4hMkINHDxi5tCOg321JIdOqOlWf68jfiqA8/VRbpvGO+rskMlr147sfdoyO26dhFWi/yvX8uwfQ8TYFdFgUfwiG3L6H8a+6d9ZtDwFkF+FOJr5QWN+2obw9vkfCrC3a6i5UgIAoXLXp0Tn+8gNVXNFnIub8NLjS1Rpv208A6Z6+NdmLVOYD/s6Pw=
  template:
    metadata:
      creationTimestamp: null
      name: staggered-live1
      namespace: default

