apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nutanix-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAyaby4IaLcCGbVZ/jlmdWF19i85GmnrBlAIQF0yQ0Nzpyh2/2LAI7G1QpFfAzeIIi+wRv4ugO9OFPcRIgrXE0J0YnnG5GNS6Av7Taf/nLGgmSPc/3Que2iaAAuij+oil/zn9KVa9s6WIVuM+psW0G5D6JBpFHKFMtGxsXo7p6QAlSMctFj38zMFnUkAvXlGvxl6GJ0q+fbv5yarHicHBL0O30F03/+oJ86NyZKxECg7HS1FJ6fQxBek7UWxgW1OhCe2LQZJPI3NuNCr6YdNGSPXHo21thYjeFgn2uhh5RwDixqb6WYb4srMB5Wxpyj6hhLmhOO+ASywZYbzVK/kpTrbmdcunbprlRi+twDBze7DmtNQaeky6nxHprqRTNtgdQN3AOSHu/vMGLZlV70pfdYOJo0TSMhJgg=
  template:
    metadata:
      creationTimestamp: null
      name: nutanix-repo
      namespace: default

