apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nutanix-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQC2URlJSvnnSXEwajKqsgq8OKINb/aR0tQN4IF1bBcfIG/SSMSX98Y/XggpI/0SN3400fVbKJ/2UTO5maR9f+neg6BdHvIHD9BloW08M44KMVUDxzckpSE2gDYBu0GiHsFDcsxWu2JZDsx4iT3jnjmESdEMd9j9TI2v8Vgoig9/2743mKQiqt4tuy9s79/htOK1ZP/CAxVMbjiiZEL093poTrL2wXPmvDW2O16UZPpwG3E8o0ND7LFYmkhOK81CzTN4nW8+RRd/nz5VPitrlPNsulgVtVjyWkZf3Mp5fjcM5liGFbhLIKU75pOmkB6D980FSOj+A4KuNelkHEpFE1svEjaixizsnW3PAaQqMbHeVtpwq5GzupBXxaLU3O7h0EB0t75D9BmOEetBOC3J7J7p/5HZuf+PXv8=
  template:
    metadata:
      creationTimestamp: null
      name: nutanix-repo
      namespace: default

