apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: testhelmrepo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCZLj0UR6Pbp3MvaDQySqeLWF1pv+HsBECsc0dDv9Sneb4SzfU4f75lqCZ9wwEk52d5midJa/sSZuxJUXWMr8aSg0ul6KWV0mdD34T8P5EcIEpxuvO1Dik3lKNgJhTAaAJdgN0HCKYW/WylySVcKvm+WheCMCntn6J5F1PZ8LG/qz7sSWCPp/+lOIfBOrneeKyzjYQw6AMcLT2xxoP4XLStAkurVagFJS56PrHT/trR6fKTWMYfeuzBLet85tx/eiyxWH+wWQX5c9F0kS65ZoBhUBBkr/2Gr4Y6af1+8ffStiQJf3GMuUHSLha+PFanB6WbZ4S2LGhSaLaoObPHJ6K4DkbxMY4FbwghU8yaQa9dcQ==
  template:
    metadata:
      creationTimestamp: null
      name: testhelmrepo
      namespace: default

