apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: testhelmrepo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBwOIpUbWiowwPocMz3IzNM70VwJ+oEzOllM+OKhZ1ZrBIFyWaCZaaZFs+kvdw4oJoFRaR77eMmrlFAR9c8z+ZuftWEGFJVGvL36FDJdS7vdTDeXBYAunchMu8IWSN4E2njD02UiojLg4vNk6pbDJsG+z2bgBBnbB/wgxzmQYcQnaqRs1ShLSddDRVNp2ioeIHgEbuCCoB335/tNOXeF5DolUkOnsfwqQA4uC+f8fxTUFqIdFkiL61ZIGgJg+nuGzhGHrZstI/FprC1ann9vXy/2c+Y1fVHXXT9eeAlaj0P9rP45ZPj2h0MjNYYCgTOt4tyQ6bSry2/Yz3fplwkDejYHPMtfV0IDpwjcg+bZtpSAA==
  template:
    metadata:
      creationTimestamp: null
      name: testhelmrepo
      namespace: default

