apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workloadrepo1
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAHnirmSC3DYvv378hAKi9YLsreup4vgOE4m20TjAV1CjzwdWVdAajKTA8WZIfSjM/qk9M/anlCkZexULedOBqcl/96MKekNTR0bDVMZFMfbJMLgFaNNbUHBNvKZuH8/INFyW3z2imqbtrzcJu8p4yFTQY2JU6mrAtVur5eCKPGj/OLYBrFoBYCsjXuqchmsaWfHblBh5H8Xb77Lq4oi/DEhXgSsoZePgkKZMPvyWq9C0eekGqQ3YyC8AIJVu3qPBD5eFC/jD/duZUmNj1mysng/QBGRi4rE5IQqnMdEGVKl3/UFrPJL/0LdMH7jjPLHmsJz05mBu+jaWVoZ8dCafW5aG3u0UQht0hveTqws/8f54VHJqDcmWsd/nnNrTi+phgyUETwOTPwIXAihlFqKAzyD+gY8CpFaWg=
  template:
    metadata:
      creationTimestamp: null
      name: workloadrepo1
      namespace: default

