apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workloadrepo1
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBMGjsC6slzy8eF1lrAXTy838PxFwaoK8UN8SKfyZYKR0muv2JSyjBTLtzcNskIeRt3iA7H4xDDFw4iNHWdwHJgVG5CSKHMjNMT0jCZdjDZVXxxvPiINS6+LywUIoZ/BKdNOtgdJ8icFglLYn5A65sCzLgKoUatcsUBdO7TMrodNMVVe8KIaDab+1vkjtPSXR7GHygYDBO1k2aelzdiC+oQznX/UWwZzUlvl45uZh4qyWNN0jaap8p5fcjVM6scQOdnL+8aOYQXM8F2P8wudEuVDv/j0OINjp8UA73bf4/qwimthCRcZiqZZD0DlUz85PGP2UZ1qKjMbZ/qQe9TDFvgPc4YFbGmjGZWg0nIshudmyTcNZE3h17gC1Z5fsEGYzYWtNr82fRiLmd7YM2nEGT2YGUsE/p07rA=
  template:
    metadata:
      creationTimestamp: null
      name: workloadrepo1
      namespace: default

