apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: aws-alb
  project: defaultproject
spec:
  agents:
  - {}
  endpoint: https://aws.github.io/eks-charts
  options: {}
  type: Helm
