apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: idp-gs6874-em
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDOUaR1IWr+IQq4bXWcVbSVRut6rvAowgWH0IEkVx9FQyLtx/oLlrQpQhRIRE8ks5Nh8ksuPuu4umHf0NPGih/WPQ5qQ0tO95XXWYMYT0IrJvnAwjnEFg33CuVhyfCrXIyVIYKtvY/kofVrAAgH1r8XXZGBKzQiA1f8fWoqL4+C2wL4V68+Xr9/fb3o9shl4QJ2AGUzxH+1QYN/rhkX3HtmSyFEIzBl8IytiVOvYJiL/+NESYrXNCArXJN7RUMUC7Dzx8DIP3XiMdMwNHPynpbZoBLGTNz/UrJDTxbIh4bbZfotjwMxq4SlESscw+wBbgbOQcJJ1Bwf8jEDvs2j3Yd4+95JdqGf+JzVCrKNR/UHP+cvMITz8Lh9fBisNAp5DBckQvmkjfPxdl4HcNBPJFPhC07T9KVk0hc=
  template:
    metadata:
      creationTimestamp: null
      name: idp-gs6874-em
      namespace: default

