apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: idp-gs6874-em
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAX1Rgi9HNjtWAo88jyBiShIuovrqdBgD8LgIobCZnXM8R2kN19E2vx9XHs2II63pxM+baZwPTtR/p7Dl+dc47h9C1nwj3LYJwNQuDMoTD4tCe5376UM6IKJaY8cnTGO6puVluV2Amkx+XrfVib0NPTjbuW31WVNvDE1Hz76Ik0BQNRDZyUPdIi11IOwLNHS1FZ61bF8kd/qYnreDf2456bMwaahLxfe1nYgdJ8Kdan7OG4pY7N1yFt1B8DL7Kpy/CSGvY7CJgUnSvG/Ep9iEty/Sad30ER11nvLgJ3+kyQWq715leDScWR7plydFi2DCJuhotF0Oecs3q+Pt88FVi/kbeLRIjOiRd8K5V7OcWSPvsUl5hHHhAFI8eZhw1mHY2aVkcVDxmoNfhUMG+sZ2rxOitPvmOJUgQ=
  template:
    metadata:
      creationTimestamp: null
      name: idp-gs6874-em
      namespace: default

