apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/nginx/nginx.yaml
    options: {}
    type: Yaml
  namespace: stag
  placement:
    selector: rafay.dev/clusterName=vijaysmks260114
  version: nginx-v2
