apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: proxy-nginx
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/proxy-nginx/proxy-nginx.yaml
    options: {}
    type: Yaml
  namespace: stag
  placement:
    selector: rafay.dev/clusterName=desktop
  version: proxy-nginx-v1
