apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: staggered-live2
  namespace: default
spec:
  encryptedData:
    variables.1.: AQDyze8nPaOqrayGyQLLCz1FhzdanxxfqLdGyoMsfjYtGv9odImxi51aVhOz2fRZE13qZEjvLycYwEhDRPQEIBA59ZGwdJh7Z34BGV5tGTKdzfPL0G02CdQ68LHnKqx1jhrlW7W1k+HqhbQHac3XVinQLUxcE8WHkBeF/8L+KjjKcyhBtAqV6wZ3+TCtGSyuA4FHCg90nWWsnLiyGdxGcEWssEF/kNdGoElFSUfP2rmhqH59XjECaY5i7g3fX1VXfkHgpgzVSRoCYAGtnUULRQxPJNmvbnyVwuHaJtgEcVnPbDLqeWUhTcg6GRY3a6NOgCoWIGtpSHD7Pa/TlyOTVeh+sDndPAe4JPkRaxELPXVEShjUy2f+BAIN
  template:
    metadata:
      creationTimestamp: null
      name: staggered-live2
      namespace: default

