apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: staggered-live2
  project: defaultproject
spec:
  secret:
    name: file://artifacts/staggered-live2/sealed-secret.yaml
  template:
    name: staggeredtest-1
    version: v3
    versionState: unspecified
  variables:
  - name: username
    options:
      override:
        type: allowed
      required: true
    value: vijaysupdatedpass
    valueType: text
  - name: password
    options:
      mask: true
      override:
        type: allowed
      required: true
      sensitive: true
    value: sealed://variables.1.
    valueType: text
