apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: staggered-live1
  project: defaultproject
spec:
  secret:
    name: file://artifacts/staggered-live1/sealed-secret.yaml
  template:
    name: staggeredtest-1
    version: v3
    versionState: unspecified
  variables:
  - name: password
    options:
      mask: true
      override:
        type: allowed
      required: true
      sensitive: true
    value: sealed://variables.0.
    valueType: text
  - name: username
    options:
      override:
        type: allowed
      required: true
    value: vijays
    valueType: text
