apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: staggeredtest2
  namespace: default
spec:
  encryptedData:
    variables.1.: AQA/tISZ8uwD4z9z3D2gnFtkDduMBIlhIKCf0qrUUoKfjZuD/Qksd+Oi1EayeINUm/OIjYcTnmKkl3OjWhRmwI9mIkQcPpH1kzoHt2VHoYoZrhJ5TrdesckOMi4oCXVLKDVJJ0kDVpgSv9NfafU0pVyyozIBBG+7jMAGQGCNgycfwd68GkK1qcWkHx5jCu7MDbqtoSNkNdVgZRIptuDk8JGki/rxCCRhTuZhmLvX2j/O8XBVn90FVdRWsfKOACf5QjSM6QyAs9WWma/rc4Myt1NAYzzrqQywdRJj14712piqF3vs3X1+YWGQaRT37eqPFQPM7j2PcS1jywKCVQ97Y1JAoLWqEcvC9hlJKm+rguBr+wXKiwlFrERw
  template:
    metadata:
      creationTimestamp: null
      name: staggeredtest2
      namespace: default

