apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: staggeredtest2
  namespace: default
spec:
  encryptedData:
    variables.1.: AQBQ9hkv49v6b6abiBPSReh2knCX1O58hMIWID7YfUIDXbB7hkZavLxWAEFbqMVSKL138KCyQ54rSP5u0FDMVphX6el9P9esDt5f4nyj9fTy9zOuQ3wPO2UkvH9pbROqDdfTcrnk+lOdYXZ9tCQcwf/82ZYgV5fLItJb/vc0dEyZXftTE9JsHdhoMja5STCz9d/ItLv41H+2aSRkI6XJZ8TVvdOLecXxC1oPJD9d/tQWVFq8e4ujOvLOW2xeluyEXEJjMxextfRVVLVO40d3ciccVB4qJ02VebcWtJHEhgLk43zlBMyfc8XmJF9e0VopBJamvWcklJr+aA8Rp6twVGYUZkgIRzc1Gg5HDNJdwBuwT6NkFx6D4O+q
  template:
    metadata:
      creationTimestamp: null
      name: staggeredtest2
      namespace: default

