apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: staggeredtest2
  namespace: default
spec:
  encryptedData:
    variables.1.: AQA7MmAAsaKoXUjKXCh4WvNc0RSf8q5+k6dgXEXGgkjWNbkckL5SwVIB8MsHzPOYPGFeuUwHGfF3SUWOWsAEN0YcsKOP4lp/JlX/GWBc7aiysSOVE5IP1qIaGietr6iufOJFRmgcA751JaOGxa28yYkmWKhyyhU46Lg2pUCMmvK4ZQJ7OXUYEVx62dz4Fxcz5/XbZYsT+TPnuAzaAsC7Wbcw59eFz5Kow6ocgwZL7YqwCnLzys86LIhMWDyQIePZJYRqfD+kcAe75c7n0iZnV8zdD7gVDZM29zPG7UW44PQYwQV6DBbPK6LoIHGb/3IP45avEhHvev14koqN5RDnoGgvhQu8stKCVAQOrdFvZzaeZPDU7WipTndH
  template:
    metadata:
      creationTimestamp: null
      name: staggeredtest2
      namespace: default

