apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: cert-manager
  project: defaultproject
spec:
  artifact:
    artifact:
      catalog: default-helm
      chartName: cert-manager
      chartVersion: v1.19.1
      valuesPaths:
      - name: file://cert-manager-values.yaml
    type: Helm
  namespace: cert-manager
  sharing: {}
  version: v1
  versionState: active
