apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rafaysync230426
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAuZfK5rlAvOve1J07XJ6S+9zWtJ6ziGkihxXGasQ57E0EWSnBwY2hfIksV3mwrNSKP0MqCjTYbQHq524xv4SHp1GVT4E714eyOH4LDQdaK64VIXBg+aUopKzeGf7fHU/F7rgWzlbLWFAQNwSCxkZ42knyb9kkpwFhLwJL+/k9Mv+rH3yZ9YoKhJTsEplpm46jhKHcz2U9WKOLo0r75ajhXHYCGBoTkovr4anMvvXiaFjtpj73/X9BxxacAwW1jfXhK+fkfcWgLoZVIxFFhhGnqrytzHTReCz/UL50X9ashzxIDY0ChqFDiEKM73dbTURWLVWtk+MbWzGEjcKwL8Q7qNzxKMdjjw5zUWPBSn7lToBhYDg8G9u1BJZI2HwID4uYoCfterVxFlST+mzuBPFg1Xm55IdUkMc4=
  template:
    metadata:
      creationTimestamp: null
      name: rafaysync230426
      namespace: default

