apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rafaysync230426
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCb7XzWqNvQGmqWlzQYHbSmJhX1qHCKzh8jpJQwIQLDYk68iApAF6WtzKYlRSIIvvQ12RgJO7DglgLAiRqEwa8VXAEbInljmGRYmzxc2tqoxLzRsYXo491ayFn9IIIcmEjj/KOnM18LYEy7tp0PpqzFY5fFuvqiUsFjtPue/0UGohExaTCCF6YKziHO+FaME2nqycg58mlOgEyrbDoCtwfTSViPCc7athI33p2PtUJM3ryH06NvIf85ClFywcn1DUPcDYeirEPf6TCugtU80UzgFIp3l8BoQZIwyPojSsZCj7vPc3DSKVg5h0ydIwsp/Alu1On9vlBprHsg5TFd1+Qk7waTjAkmve8CmofYz7XBRLN89YWVIu1Ukn4uYN2DdF+km/G4XhBYlD7/QSYDGETdJ9s2lAfw+A4=
  template:
    metadata:
      creationTimestamp: null
      name: rafaysync230426
      namespace: default

