apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: mag1
  project: defaultproject
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: vijaysmks141125
    - key: rafay.dev/clusterName
      value: vijayseks11251
  resourceQuotas: {}
