apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rep-drift-action: deny
  labels:
    k8smgmt.io/project: defaultproject
    k8smgmt.io/update-time: "1783987415345069291"
    kubernetes.io/metadata.name: my-namespace
    name: my-namespace
    rep-addon: firstaddon
    rep-cluster: kggpwjk
    rep-cluster-name: vijaysmks260630
    rep-drift-reconcillation: enabled
    rep-organization: 6knr742
    rep-partner: rx28oml
    rep-placement: kvjxqry
    rep-project: d2wpz6k
    rep-project-name: defaultproject
    rep-workloadid: 2w55gqj
  name: my-namespace
  project: defaultproject
spec:
  drift:
    action: Deny
    enabled: true
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: vijaysmks260630
  resourceQuotas: {}
