apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  annotations:
    rafay.dev/audit_type: BROWSER||Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
      AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
    rafay.dev/audit_user: vijaysamanthapuri@rafay.co
    rafay.dev/audit_user_group: Organization Read Only,Organization Admins
  name: vijaysaddon1
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/vijaysaddon1/webapp-python-1.0.0.tgz
    type: Helm
  namespace: vijaystestns
  sharing: {}
  version: v1
  versionState: active
